[METADATA]

language = English
# The path of your song folder
songs_folder_path =
# Filename, do NOT put in the .txt extension - just the name of the folder/txt file
filename = Example artist - Example song

[Default]
# Don't want to play around with the settings? Set this to True
# overwrites notegap and multiplier
easy_mode = True


# ===== MORE ADVANCED SETTINGS BELOW, CHANGE IF easy_mode = False ===== #

[Config]
# if your song is slow/has long breaks, increase multiplier *2, if fast/short breaks, decrease /2
multiplier = 1
# default 16 OR 10, depending on structure of song
notegap = 16

overwrite_file = False
trim_long_notes = False
lengthen_short_notes = True


[Other]
# default 128
longest_note_length = 128
# default 2 or 1
note_spacing = 2
# default 2
shortest_note_length = 4
# default 7.95, don't change unless you know what you're doing
careful_notegap_length = 7.95
# default 0.5, don't change unless you know what you're doing
careful_notegap_multiplier = 0.5

# default False
even_breaks = False
# default 32 or 64
even_breaks_measure = 32
# default 32 or 0
even_breaks_first_note_offset = 0